logging:
  level:
    root: INFO

rss:
  fetch:
    thread-pool:
      core-size: 5
      max-size: 10
      queue-capacity: 100
      keep-alive-seconds: 60
    batch-size: 100
    check-interval-seconds: 10

